Repository HYF-Class19/ahmo-frontend-class19, pull requests merged in 2023-04, with the labels that each got.

#43 Search
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatMenu/index.tsx
  src/components/chat/ChatType/index.tsx
  src/components/chat/CreateChatDialog/index.tsx
  src/components/game/CreateGameDialog/index.tsx
  src/components/shared/SearchBar/index.tsx
  src/components/shared/SearchResult/index.tsx
  src/models/IUser.ts
  src/pages/profile/[id].tsx
  src/services/api.ts
  src/services/authService.ts
  src/utils/chatHelpers.ts
Labels: Development

#45 Create chats
  src/components/chat/ChatMenu/index.tsx
  src/components/chat/ChatTabs/index.tsx
  src/components/chat/ChatType/index.tsx
  src/components/chat/CreateChatDialog/CreateChatDialog.module.scss
  src/components/chat/CreateChatDialog/index.tsx
  src/components/game/GameTextField/index.tsx
  src/components/shared/CreateItem/CreateItem.module.scss
  src/components/shared/CreateItem/index.tsx
  src/components/shared/CustomCheck/index.tsx
  src/components/shared/CustomRadio/index.tsx
  src/components/shared/SearchBar/index.tsx
  src/components/shared/SearchResult/index.tsx
  src/pages/chat/index.tsx
  src/pages/index.tsx
  src/services/chatService.ts
  src/styles/Main.module.scss
  src/styles/globals.scss
  src/styles/theme.ts
  src/utils/createChatValidation.ts
Labels: programming

#49 modified files: modified: package-lock.json
  package-lock.json
  package.json
  public/puzzles.png
  src/components/card/card.module.scss
  src/components/card/index.tsx
  src/components/shared/Footer/Footer.module.scss
  src/components/shared/Footer/index.tsx
  src/components/shared/Header/Header.module.scss
  src/components/shared/Header/index.tsx
  src/components/welcome-text/index.tsx
  src/components/welcome-text/text.module.scss
  src/pages/index.tsx
  src/styles/globals.scss
Labels: programming

#52 finish start round button
  src/components/game/GameRound/GameRound.module.scss
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/index.tsx
  src/components/shared/Header/index.tsx
  src/models/IGame.ts
  src/pages/chat/index.tsx
  src/services/api.ts
  src/services/roundServive.ts
  src/store/slices/roundSlice.ts
Labels: programming

#53 Game
  src/components/chat/ChatType/index.tsx
  src/components/chat/Conversation/index.tsx
  src/components/chat/CreateChatDialog/index.tsx
  src/components/game/GameActions.tsx
  src/components/game/GameBox/GameBox.module.scss
  src/components/game/GameBox/index.tsx
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/index.tsx
  src/components/game/RoundData/index.tsx
  src/components/game/TruthDareField/index.tsx
  src/components/game/TruthDareRound/index.tsx
  src/components/shared/Header/index.tsx
  src/components/shared/SearchBar/index.tsx
  src/components/shared/SearchResult/index.tsx
  src/models/IChat.ts
  src/services/chatService.ts
  src/services/roundServive.ts
  src/utils/round-helper.ts
Labels: programming

#54 finish the words game
  src/components/chat/CreateChatDialog/index.tsx
  src/components/game/GameBox/index.tsx
  src/components/game/GameHeader/index.tsx
  src/components/game/GameRound/index.tsx
  src/components/game/TruthDareField/index.tsx
  src/components/game/WordsTextField/index.tsx
  src/models/IGame.ts
  src/services/api.ts
  src/services/roundServive.ts
Labels: programming

#56 Game
  public/img/chat-template.jpg
  public/img/game-template.jpg
  public/img/send.svg
  src/components/auth/LoginForm.tsx
  src/components/chat/ChatBox/ChatBox.module.scss
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatType/index.tsx
  src/components/game/GameBox/GameBox.module.scss
  src/components/game/GameBox/index.tsx
  src/components/game/GameInput.tsx
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/GameTextField.module.scss
  src/components/game/GameTextField/index.tsx
  src/components/game/TruthDareField/index.tsx
  src/components/game/WordsTextField/index.tsx
  src/components/shared/GameAlert.tsx
  src/components/shared/SelectChatTemplate/SelectChatTemplate.module.scss
  src/components/shared/SelectChatTemplate/index.tsx
  src/components/shared/SendIcon/SendIcon.module.scss
  src/components/shared/SendIcon/index.tsx
  src/services/api.ts
  src/styles/Chat.module.scss
  src/utils/round-helper.ts
  src/utils/socket.ts
Labels: Development

#59 added and modified this folders modified: src/components/card/card…
  public/chat-pic.jpg
  public/hi-hey.png
  src/components/card/card.module.scss
  src/components/card/index.tsx
  src/components/shared/Header/Header.module.scss
  src/components/welcome-text/index.tsx
  src/pages/index.tsx
Labels: programming

#60 fix games chat conflicts
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatTextarea/index.tsx
  src/components/chat/Conversation/index.tsx
  src/components/game/GameBox/index.tsx
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/index.tsx
  src/components/game/RoundMove/index.tsx
  src/components/game/TruthDareField/index.tsx
  src/components/game/WordsTextField/index.tsx
  src/pages/chat/index.tsx
  src/services/chatService.ts
  src/services/gameService.ts
  src/services/messageService.ts
  src/services/roundServive.ts
  src/store/slices/chatSlice.ts
  src/utils/socket.ts
Labels: bug, programming

#61 Profilepage
  src/components/profile/ChangePasswordForm.tsx
  src/components/profile/EditableText.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/profile/SideMenuButton.tsx
  src/components/profile/avatar.tsx
  src/components/profile/customButton.tsx
  src/components/profile/mainContent.tsx
  src/components/shared/Header/index.tsx
  src/pages/profile/index.tsx
Labels: programming

#64 update chat page styling
  src/components/chat/ChatBox/ChatBox.module.scss
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatHeader/ChatHeader.module.scss
  src/components/chat/ChatHeader/index.tsx
  src/components/chat/ChatMenu/index.tsx
  src/components/chat/ChatTabs/ChatTabs.module.scss
  src/components/chat/ChatTabs/index.tsx
  src/components/chat/ChatTextarea/index.tsx
  src/components/chat/ChatType/index.tsx
  src/components/chat/Conversation/Conversation.module.scss
  src/components/chat/Message/Message.module.scss
  src/components/chat/Message/index.tsx
  src/components/game/GameBox/GameBox.module.scss
  src/components/game/GameBox/index.tsx
  src/components/game/GameHeader/GameHeader.module.scss
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/GameTextField.module.scss
  src/components/game/WordsTextField/index.tsx
  src/components/shared/SearchBar/index.tsx
  src/components/shared/SearchResult/index.tsx
  src/pages/_app.tsx
  src/pages/chat/index.tsx
  src/services/chatService.ts
  src/services/gameService.ts
  src/services/roundServive.ts
  src/store/slices/chatSlice.ts
  src/styles/Chat.module.scss
  src/utils/chatHelpers.ts
Labels: Design, Development

#67 Home page updated
  src/components/shared/ColoredButton.tsx
  src/components/shared/Footer/index.tsx
  src/components/shared/home-page/Footer/Footer.module.scss
  src/components/shared/home-page/Footer/index.tsx
  src/components/shared/home-page/Header/Header.module.scss
  src/components/shared/home-page/Header/index.tsx
  src/components/shared/home-page/card/Card.module.scss
  src/components/shared/home-page/card/index.tsx
  src/components/shared/home-page/welcome-text/Text.module.scss
  src/components/shared/home-page/welcome-text/index.tsx
  src/components/welcome-text/index.tsx
  src/layouts/MainLayout.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/services/api.ts
  src/styles/theme.ts
Labels: Development

#68 Game
  src/components/chat/Conversation/index.tsx
  src/components/chat/Message/Message.module.scss
  src/components/chat/Message/index.tsx
  src/components/shared/HeaderMenu.tsx
  src/components/shared/home-page/Header/Header.module.scss
  src/components/shared/home-page/Header/index.tsx
  src/pages/_app.tsx
  src/utils/chatHelpers.ts
Labels: Design, Development

#72 Chat setting
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatHeader/index.tsx
  src/components/chat/ChatMenu/index.tsx
  src/components/chat/ChatSetting/index.tsx
  src/components/chat/Conversation/index.tsx
  src/components/chat/CreateChatDialog/index.tsx
  src/components/game/GameBox/index.tsx
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/index.tsx
  src/components/game/RoundData/index.tsx
  src/components/game/TruthDareField/index.tsx
  src/components/game/WordsTextField/index.tsx
  src/components/shared/GameAlert.tsx
  src/components/shared/Header/Header.module.scss
  src/components/shared/Header/index.tsx
  src/layouts/MainLayout.tsx
  src/models/IChat.ts
  src/pages/index.tsx
  src/services/api.ts
  src/services/chatService.ts
  src/services/gameService.ts
  src/store/slices/chatSlice.ts
  src/store/slices/roundSlice.ts
  src/utils/chatHelpers.ts
Labels: bug, Development

#73 add images, improve profile logic
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatHeader/index.tsx
  src/components/chat/ChatSetting/index.tsx
  src/components/chat/Conversation/index.tsx
  src/components/chat/CreateChatDialog/index.tsx
  src/components/chat/Message/index.tsx
  src/components/game/GameHeader/index.tsx
  src/components/game/RoundMove/index.tsx
  src/components/game/TruthDareRound/index.tsx
  src/components/profile/EditableText.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/profile/avatar.tsx
  src/components/shared/CreateItem/index.tsx
  src/components/shared/CustomAvatar.tsx
  src/components/shared/Header/index.tsx
  src/components/shared/HeaderMenu.tsx
  src/components/shared/SearchResult/index.tsx
  src/models/IChat.ts
  src/models/IUser.ts
  src/pages/profile/index.tsx
  src/services/api.ts
  src/services/authService.ts
  src/store/slices/chatSlice.ts
  src/store/slices/userSlice.ts
Labels: Development

#75 fixing design issues
  public/emoji-img.png
  src/components/shared/home-page/card/index.tsx
  src/components/shared/home-page/welcome-text/index.tsx
  src/layouts/background-image.png
  src/pages/auth/login.tsx
  src/pages/auth/register.tsx
  src/pages/index.tsx
  src/pages/profile/[id].tsx
  src/services/authService.ts
  src/store/slices/menuSlice.ts
  src/styles/globals.scss
Labels: Design

#77 finish profile logic
  .eslintrc.json
  src/components/auth/FormWrapper.tsx
  src/components/auth/LoginForm.tsx
  src/components/chat/ChatHeader/index.tsx
  src/components/chat/ChatSetting/index.tsx
  src/components/profile/ChangePasswordForm.tsx
  src/components/profile/EditableText.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/shared/CustomAvatar.tsx
  src/components/shared/FormField.tsx
  src/components/shared/Header/index.tsx
  src/components/shared/HeaderMenu.tsx
  src/hooks/useUpdateUser.ts
  src/models/IUser.ts
  src/pages/profile/[id].tsx
  src/pages/profile/index.tsx
  src/services/api.ts
  src/services/authService.ts
  src/services/gameService.ts
  src/store/slices/userSlice.ts
  src/utils/FormSchemas.ts
Labels: Development

#79 Errors handling
  src/components/auth/LoginForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatHeader/index.tsx
  src/components/chat/ChatMenu/index.tsx
  src/components/chat/ChatType/index.tsx
  src/components/chat/Conversation/index.tsx
  src/components/chat/CreateChatDialog/index.tsx
  src/components/chat/Message/index.tsx
  src/components/game/GameBox/index.tsx
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/index.tsx
  src/components/game/RoundData/index.tsx
  src/components/game/TruthDareField/index.tsx
  src/components/game/WordsTextField/index.tsx
  src/components/shared/Header/index.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/chat/index.tsx
  src/services/gameService.ts
  src/store/slices/menuSlice.ts
  src/store/slices/userSlice.ts
  src/styles/globals.scss
  src/utils/chatHelpers.ts
  src/utils/redirect.ts
  src/utils/round-helper.ts
  src/utils/socket.ts
Labels: Development

#80 Errors handling
  src/components/chat/ChatMenu/index.tsx
  src/components/chat/ChatTabs/index.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/shared/SearchBar/index.tsx
  src/components/shared/SearchResult/index.tsx
  src/components/shared/home-page/card/Card.module.scss
  src/components/shared/home-page/card/index.tsx
  src/hooks/useDebounce.ts
  src/hooks/useDebouncedSearchUsersQuery.ts
  src/pages/chat/index.tsx
  src/pages/profile/[id].tsx
  src/store/slices/menuSlice.ts
Labels: Development

#82 finish mobile view chats
  src/components/chat/ChatBox/ChatBox.module.scss
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatHeader/ChatHeader.module.scss
  src/components/chat/ChatHeader/index.tsx
  src/components/chat/ChatSetting/index.tsx
  src/components/chat/ChatTabs/ChatTabs.module.scss
  src/components/chat/ChatTabs/index.tsx
  src/components/chat/Message/Message.module.scss
  src/components/game/GameBox/GameBox.module.scss
  src/components/game/GameBox/index.tsx
  src/components/game/GameHeader/GameHeader.module.scss
  src/components/game/GameHeader/index.tsx
  src/components/game/GameRound/GameRound.module.scss
  src/components/game/GameTextField/GameTextField.module.scss
  src/components/game/GameTextField/index.tsx
  src/components/game/RoundMove/RoundMove.module.scss
  src/components/game/TruthDareField/index.tsx
  src/hooks/useIsMobile.ts
  src/pages/chat/index.tsx
  src/styles/Chat.module.scss
  src/styles/globals.scss
Labels: Design, Development

#84 Home page
  src/components/shared/home-page/Footer/index.tsx
Labels: Design, Development

#87 Errors handling
  src/components/chat/ChatBox/index.tsx
  src/components/chat/ChatSetting/ChatSetting.module.scss
  src/components/chat/ChatSetting/index.tsx
  src/components/game/GameActions.tsx
  src/components/game/GameBox/index.tsx
  src/components/game/GameRound/GameRound.module.scss
  src/components/game/GameRound/index.tsx
  src/components/game/GameTextField/GameTextField.module.scss
  src/components/game/TruthDareRound/index.tsx
  src/components/profile/ChangePasswordForm.tsx
  src/components/profile/EditableText.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/profile/mainContent.tsx
  src/pages/profile/[id].tsx
  src/services/chatService.ts
  src/utils/round-helper.ts
Labels: Development

#93 some cosmetic issues
  src/components/game/GameRound/GameRound.module.scss
  src/components/profile/ChangePasswordForm.tsx
  src/components/shared/CustomDrawer.tsx
  src/components/shared/Header/Header.module.scss
  src/components/shared/SearchBar/index.tsx
  src/services/gameService.ts
Labels: Design

#94 some cookie changes and linking
  src/components/auth/LoginForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/shared/CustomDrawer.tsx
  src/components/shared/Header/index.tsx
  src/components/shared/home-page/card/index.tsx
  src/pages/api/hello.ts
  src/services/api.ts
Labels: bug, Design

#96 Learnmore page
  src/pages/learn-more.tsx
  src/styles/globals.scss
Labels: Development

#97 learnmore page fixing issues
  src/components/shared/BurgerMenu/index.tsx
  src/pages/learn-more.tsx
  src/styles/LearnMore.module.scss
  src/styles/globals.scss
Labels: bug

#99 fixing chat creating bug
  src/components/chat/CreateChatDialog/index.tsx
Labels: bug
